# Generated by Django 4.2.4 on 2023-09-30 06:50

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='blogimg')),
                ('content', models.TextField()),
                ('Sub_Content', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ClintProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clintprofile')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('Sub_Content', models.TextField(max_length=300)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleryimg')),
            ],
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliderimg')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newsimg')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('sub_Content', models.TextField(max_length=300)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='PollingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('opening_Poll', models.IntegerField(max_length=150)),
                ('Exit_Poll', models.IntegerField(max_length=200)),
                ('Result', models.IntegerField(max_length=200)),
                ('image', models.ImageField(upload_to='pollings')),
                ('content', models.TextField()),
                ('video', embed_video.fields.EmbedVideoField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_Title', models.CharField(max_length=50)),
                ('First_Service_Image', models.ImageField(upload_to='servimg')),
                ('First_Service_Content', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Testomonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='CabinetMembers')),
                ('name', models.CharField(max_length=100)),
                ('memberpost', models.CharField(max_length=100)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
