# Generated by Django 4.2.4 on 2023-09-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pollingresult_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingresult',
            name='title',
        ),
    ]
