# Generated by Django 4.2.4 on 2023-09-30 06:57

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_pollingresult_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pollings')),
                ('content', models.TextField()),
                ('video', embed_video.fields.EmbedVideoField()),
                ('state', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('Ruling_Party', models.CharField(max_length=200)),
                ('Result', models.IntegerField(max_length=200)),
            ],
        ),
    ]
