# Generated by Django 4.2.4 on 2023-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_electionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionresult',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
