# Generated by Django 4.2.4 on 2023-09-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_electionresult_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResultDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Constituency_Name', models.CharField(max_length=200)),
                ('Candidate_Name', models.CharField(max_length=200)),
                ('Party', models.CharField(max_length=200)),
                ('Level', models.CharField(max_length=200)),
                ('Votes', models.CharField(max_length=200)),
                ('Margin', models.CharField(max_length=200)),
            ],
        ),
    ]
