# Generated by Django 4.2.4 on 2023-09-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_electionresultdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionresultdetails',
            name='Margin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='electionresultdetails',
            name='Votes',
            field=models.IntegerField(),
        ),
    ]
