# Generated by Django 4.2.4 on 2023-09-30 15:10

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_electionresult_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionresultdetails',
            name='content',
        ),
        migrations.RemoveField(
            model_name='electionresultdetails',
            name='image',
        ),
        migrations.RemoveField(
            model_name='electionresultdetails',
            name='title',
        ),
        migrations.RemoveField(
            model_name='electionresultdetails',
            name='video',
        ),
        migrations.AddField(
            model_name='electionresult',
            name='Result',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electionresult',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electionresult',
            name='image',
            field=models.ImageField(default=0, upload_to='pollings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electionresult',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electionresult',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
