# Generated by Django 4.2.4 on 2023-09-30 15:26

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_electionresult_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionresult',
            name='Ruling_Party',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='image',
            field=models.ImageField(blank=True, upload_to='pollings'),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='electionresult',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
