# Generated by Django 4.2.4 on 2023-09-30 15:31

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_electionresultdetails_candidate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Sub_Content',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='blogimg'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clintprofile',
            name='Sub_Content',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='clintprofile',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clintprofile',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='clintprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='clintprofile'),
        ),
        migrations.AlterField(
            model_name='clintprofile',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clintprofile',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='galleryimg'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=models.ImageField(blank=True, upload_to='sliderimg'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='image',
            field=models.ImageField(blank=True, upload_to='newsimg'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='sub_Content',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='pollingresult',
            name='Exit_Poll',
            field=models.IntegerField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pollingresult',
            name='Result',
            field=models.IntegerField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pollingresult',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pollingresult',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pollingresult',
            name='image',
            field=models.ImageField(blank=True, upload_to='pollings'),
        ),
        migrations.AlterField(
            model_name='pollingresult',
            name='opening_Poll',
            field=models.IntegerField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pollingresult',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pollingresult',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='First_Service_Content',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='First_Service_Image',
            field=models.ImageField(blank=True, upload_to='servimg'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='Service_Title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='testomonials',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testomonials',
            name='image',
            field=models.ImageField(blank=True, upload_to='CabinetMembers'),
        ),
        migrations.AlterField(
            model_name='testomonials',
            name='memberpost',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testomonials',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testomonials',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
