# Generated by Django 4.2.4 on 2023-10-02 10:00

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_blogpost_sub_content_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
