# Generated by Django 4.2.4 on 2023-10-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_servicepage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionresultdetails',
            name='partyname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='electionresultdetails',
            name='parylogo',
            field=models.ImageField(blank=True, upload_to='partylogo'),
        ),
        migrations.AddField(
            model_name='electionresultdetails',
            name='seats',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
