# Generated by Django 4.2.4 on 2023-10-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_electionseatsandparty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcommingElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True)),
                ('Ruling_Party', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
