# Generated by Django 4.2.4 on 2023-10-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_parylogo_electionseatsandparty_partylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='cabinet_member')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('desination', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
